offline-engine-web: dev

spring.servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

server:
  port: 18081
#  address: 0.0.0.0
  servlet:
    context-path: /api
#
#spring.datasource:
#  offline-engine:
#    url: jdbc:mysql://mysql-data-dev-master.int.xiaohongshu.com:33071/offline_engine_platform?useSSL=false&useTimezone=true&serverTimezone=Asia/Shanghai
#    username: offline_engine_platform_rw
#    password: HlBXkQjbNkhsd9*I
#    type: com.alibaba.druid.pool.DruidDataSource
#    initialSize: 5
#    minIdle: 10
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    keepAlive: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    useGlobalDataSourceStat: true
#    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#    filters: stat,wall,log4j2

logging:
  level:
    root: info


